### ISSUE TITLE
Deployment Checklist

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/universal-credit-support#180]
- [x] Set up heroku with automatic deployment 
- [x] Connect heroku to domain 
- [x] Ensure all log in info and passwords are in the admin doc
- [x] Set up analytics
- [x] Update documentation
- [x] Ramy to switch AWS over to Hyde's
