### ISSUE TITLE
User Testing - UX

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/universal-credit-support#46]
### Summary 
We want to use an interactive design prototype to carry out testing with our potential users. This lets us test and validate the user journeys and stories we have built, making sure the tool can be used in the way we intend it to be used, and then making any changes.

By doing this we can really define on the most essential features and make changes at the design stage which is always quicker to do than in development stage. 

**In addition...**
We are also going to test the first iteration of the digital app. This will let us assess initial thoughts of the tool in an actual digital, fully interactive format 

### Tasks:
**Booking in user tests**
This has been tackled - refer to #8 

**Preparing for user tests**
- [x] Add link to the Figma prototype
- [x] Add link to the MVP
- [x] Add link to User Testing script(s)
- [x] Add link to User Testing Feedback Form

**Storing testing results**
- [x] Store the first round UX / low res user testing sessions in the link below

### Overview of testing schedules, scripts and feedback pages: 
https://www.notion.so/User-Testing-371fc29628f542aa8e021a5be51af3f8

### Prototype links
In the notion doc scripts

**Comment by thejoefriel** [comment]
Hey @maggiehoughton @Katie-Hyde - sorry for the delay on this! We should have all the prototypes with you within the hour. In the meantime, here is a link to the User Testing documentation. 

You will notice there are 3 scripts (one for each user type). If you're ok to look over them today / Monday, and let me know any other questions we should put in please that would be great! In the doc I've also included a reminder of what we're looking to test broadly with these sessions. 

https://www.notion.so/User-Testing-371fc29628f542aa8e021a5be51af3f8

Thanks!

**Comment by maggiehoughton** [comment]
@thejoefriel I can't access the above user testing docs? Says I need permission from Jem. I'm logging in with margrethehoughton@gmail.com (some as the main notion board)

**Comment by maggiehoughton** [comment]
User testing scripts look great- thanks!

**Comment by thejoefriel** [comment]
Oh sorry @maggiehoughton is it working now?

**Comment by thejoefriel** [comment]
Hey @maggiehoughton just done first two interviews with income officers. Went well :) 
Obviously I'll collate everything properly once we get through the majority of the sessions, but if you're curious about raw feedback, feel free to keep an eye on this document where I'll be storing all the notes: https://www.notion.so/UX-Testing-Feedback-0e186f12c72c4955916b05a87ad09eaf

**Comment by maggiehoughton** [comment]
@thejoefriel I've absolutely loved checking back to read the user testing notes today!

**Comment by thejoefriel** [comment]
Ah great @maggiehoughton ! Yeah I saw you on the notion when I was speaking to one of the claimants so you got to see notes being added in real time haha!

**Comment by maggiehoughton** [comment]
In my chat with our digital manager yesterday she invited me to their team meeting this afternoon to talk about the project. I was going to share the claimant/advisor figma with them. She suggested they offer feedback from a digital-comms-team-in-the-social-housing-sector POV, so are you OK if I just ask them to drop any comments of suggestions into a google doc (as they may materialise after I log out lunchtime tomorrow)?

**Comment by maggiehoughton** [comment]
@thejoefriel William K said he was still waiting to hear back re change of date from 4th to 2nd? Edna has now found your email in her spam and will book in asap.
