### ISSUE TITLE
Update local storage tracker

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/universal-credit-support#66]
**Summary**
We currently have set up to store the users progress based on local storage. We are still doing this. However, we probably need to update considering the content now comes from the backend and could change (e.g. if they add further items to a step checklist)

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [x] Use the controller to get content from back end #65 
- [x] If in local storage we have that the user has completed step then keep completed (even if more tasks added)
- [x] Check items against those checked for that step in local storage
    - [x] Add any new items to local storage
    - [x] If a checklist item is marked as complete in local storage then that item is still ticked
