### ISSUE TITLE
Update Step (Front End)

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/universal-credit-support#68]
__Related issue(s)__

#65 will have set up the back end to return all the step content

__Wireframe link__
https://www.figma.com/file/2b1vIUlRczjuwhWr9cE9OY/Wireframes?node-id=1831%3A1884
Always remember desktop view as well

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [x] Use #65 to get data from back end 
- [x] Update step page in line with wireframes
- [x] Ensure local storage still gets updated as items are ticked off #66 
- [x] Update desktop to use new layout #60 
- [x] For eligibility, the benefit calculator link comes from the database
